# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Forgot_Password.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Forgot_password(object):
    def setupUi(self, Forgot_password):
        Forgot_password.setObjectName("Forgot_password")
        Forgot_password.resize(400, 300)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        Forgot_password.setFont(font)
        self.label = QtWidgets.QLabel(Forgot_password)
        self.label.setGeometry(QtCore.QRect(30, 20, 71, 51))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Forgot_password)
        self.label_2.setGeometry(QtCore.QRect(110, 10, 191, 71))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Forgot_password)
        self.label_3.setGeometry(QtCore.QRect(30, 100, 81, 31))
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(Forgot_password)
        self.lineEdit.setGeometry(QtCore.QRect(100, 110, 181, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(Forgot_password)
        self.pushButton.setGeometry(QtCore.QRect(250, 210, 91, 31))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Forgot_password)
        QtCore.QMetaObject.connectSlotsByName(Forgot_password)

    def retranslateUi(self, Forgot_password):
        _translate = QtCore.QCoreApplication.translate
        Forgot_password.setWindowTitle(_translate("Forgot_password", "Forgot_Password"))
        self.label.setText(_translate("Forgot_password", "Question:"))
        self.label_2.setText(_translate("Forgot_password", "BLABLA"))
        self.label_3.setText(_translate("Forgot_password", "Answer:"))
        self.pushButton.setText(_translate("Forgot_password", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Forgot_password = QtWidgets.QWidget()
    ui = Ui_Forgot_password()
    ui.setupUi(Forgot_password)
    Forgot_password.show()
    sys.exit(app.exec_())
