# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Other.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Other2(object):
    def setupUi(self, Other2):
        Other2.setObjectName("Other2")
        Other2.resize(400, 300)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        Other2.setFont(font)
        self.pushButton = QtWidgets.QPushButton(Other2)
        self.pushButton.setGeometry(QtCore.QRect(260, 200, 81, 31))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Other2)
        self.label.setGeometry(QtCore.QRect(40, 50, 81, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Other2)
        self.label_2.setGeometry(QtCore.QRect(40, 110, 71, 21))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(Other2)
        self.lineEdit.setGeometry(QtCore.QRect(120, 60, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Other2)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 110, 113, 20))
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.radioButton = QtWidgets.QRadioButton(Other2)
        self.radioButton.setGeometry(QtCore.QRect(80, 160, 131, 17))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.pushButton_2 = QtWidgets.QPushButton(Other2)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 240, 101, 23))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(7)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Other2)
        QtCore.QMetaObject.connectSlotsByName(Other2)

    def retranslateUi(self, Other2):
        _translate = QtCore.QCoreApplication.translate
        Other2.setWindowTitle(_translate("Other2", "Other2"))
        self.pushButton.setText(_translate("Other2", "Entry"))
        self.label.setText(_translate("Other2", "Username:"))
        self.label_2.setText(_translate("Other2", "Password:"))
        self.radioButton.setText(_translate("Other2", "Remember me"))
        self.pushButton_2.setText(_translate("Other2", "Forgot my password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Other2 = QtWidgets.QWidget()
    ui = Ui_Other2()
    ui.setupUi(Other2)
    Other2.show()
    sys.exit(app.exec_())
